Repository Coppeloons/NoteShare, pull requests merged in 2023-04, with the labels that each got.

#101 Add Dockerfile and docker-compose.yaml
  Dockerfile
  docker-compose.yaml
  src/main/resources/application.properties
Labels: enhancement, VG

#110 Make logo link to welcome page
  src/main/resources/templates/_fragments.html
Labels: enhancement

#113 Add alert in publishNote.js
  src/main/resources/static/script/publishNote.js
Labels: enhancement

#115 Start working on 1.0.1-SNAPSHOT
  pom.xml
Labels: documentation
